version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: selenium/standalone-chrome:3.11.0
      - image: cimg/node:19.3.0-browsers
    steps:
      - run:
          name: something
          command: |
            # Install Chrome driver
            - curl http://chromedriver.storage.googleapis.com/2.23/chromedriver_linux64.zip | gzip -dc > chromedriver
            - chmod +x chromedriver
            # Install Selenium
            - curl http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar > selenium-server-standalone.jar
            - java -jar selenium-server-standalone.jar -trustAllSSLCertificates -Dwebdriver.chrome.driver=chromedriver
          background: true
      - checkout
      - run:
          name: Run Tests
          command: mvn test
