version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Download ChromeDriver
          command: |
            wget https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
      - run:
          name: Set up environment variables
          command: |
            echo 'export PATH=$PATH:~/chromedriver' >> $BASH_ENV
      - run:
          name: Install Maven
          command: |
            sudo apt-get update && sudo apt-get install -y maven
      - run:
          name: Run tests with Maven
          command: |
            mvn test
      - store_test_results:
          path: ~/project/target/surefire-reports
