version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: selenium/standalone-chrome:3.11.0
      - image: cimg/node:19.3.0-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Run Tests
          command: |
            mvn test
