version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
      - image: selenium/standalone-chrome:3.11.0

    working_directory: ~/circleCI_Selenium_Demo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - run:
          name: create docker network
          command: docker network create grid
      - run:
          name: install selenium-hub
          command: docker run -d --rm -p 4444:4444 --net grid --name selenium-hub selenium/hub:3.11.0
      - run:
          name: install selenium node
          command: docker run -d --rm --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-chrome:3.11.0
      - run: mvn clean test
