version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Start Selenium Server
          run: java -jar selenium-server-4.8.0.jar hub
      - run:
          name: Run tests with Maven
          command: mvn clean test